sudo: required
language: node_js
node_js:
  - "8"
  - "10"
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - cassandra
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "10"
